name: Backend CI

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
  pull_request:
    branches: [main]
    paths:
      - "backend/**"

jobs:
  build:
    name: Build Spring Boot Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Build with Maven
        working-directory: ./backend
        run: mvn clean package

      - name: Upload backend jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: backend/target/*.jar
          retention-days: 7

  verify:
    name: Verify Jar Runs
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: "Chcking env varibales"
        env:
          API_KEY: ${{ secrets.DUMMY_API_KEY }}
          API_KEY2: ${{ var.DUMMY_API_KEY2 }}
        run: |
          echo "Using API key to authenticate..."
          echo "Key length check: ${#API_KEY} characters"
          echo "Second key length check: ${#API_KEY} characters"
          echo "Second key length check: ${#API_KEY2} characters"
      - name: Download backend jar artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-jar
          path: ./downloaded-jar

      - name: List downloaded contents
        run: ls -la ./downloaded-jar

      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Start the jar and check health endpoint
        run: |
          nohup java -jar ./downloaded-jar/*.jar > app.log 2>&1 &
          sleep 10
          curl -f http://localhost:8080/api/health
